### ISSUE TITLE
Update dependencies and track release time

### ISSUE THREAD

**Issue by bengolder** [codeforamerica/honeycrisp-gem#296]
[We have a variety of dependencies to update on the Honeycrisp gem](https://github.com/codeforamerica/honeycrisp-gem/security/dependabot).
Once we update dependencies, we should release a new patch version (v0.10.5) of the gem.

Once we have a new patch version merged, we will use it as an opportunity to track a baseline measure of the time to get honeycrisp updates merged into shiba, gcf-backend, and vita-min..

## Tasks

- [x] high severity
  - [x] axios
    - a dependency of `@percy/agent`, [upgrading to `@percy/cli` removes this as a dependency](https://github.com/codeforamerica/honeycrisp-gem/pull/297)
  - [x] addressable
    - updated in [PR 298](https://github.com/codeforamerica/honeycrisp-gem/pull/298)
  - [x] glob-parent
    - gets updated when [upgrading to `@percy/cli`](https://github.com/codeforamerica/honeycrisp-gem/pull/297)
  - [x] bundler
    - updated in [PR 298](https://github.com/codeforamerica/honeycrisp-gem/pull/298)
  - [x] lodash
    - a dependency of `@percy/agent`, [upgrading to `@percy/cli` removes this as a dependency](https://github.com/codeforamerica/honeycrisp-gem/pull/297)
  - [x] actionpack
    - updated in [PR 298](https://github.com/codeforamerica/honeycrisp-gem/pull/298)
- [x] moderate severity
  - [x] color-string
    - a dependency of `@percy/agent`, [upgrading to `@percy/cli` removes this as a dependency](https://github.com/codeforamerica/honeycrisp-gem/pull/297)
  - [x] ws
    - gets updated when [upgrading to `@percy/cli`](https://github.com/codeforamerica/honeycrisp-gem/pull/297)
  - [x] nokogiri
    - updated in [PR 298](https://github.com/codeforamerica/honeycrisp-gem/pull/298)
- [x] Update honeycrisp-gem dependencies and merge into `main`
- [x] Create a new patch release (v0.10.5)
- [x] Create [PR to shiba](https://github.com/codeforamerica/shiba/pull/422) (if updates affect CSS output) & track the amount of work - **30 mins**
- [x] ~Resolve any issues revealed by Percy on shiba  & track the amount of work~ No issues found
- [x] Create [PR to gcf-backend](https://github.com/codeforamerica/gcf-backend/pull/6715)  & track the amount of work - **30 mins**
- [x] ~Resolve any issues revealed by Percy on gcf-backend  & track the amount of work~ No issues found
- [x] Create [PR to vita-min](https://github.com/codeforamerica/vita-min/pull/1639) & track the amount of work - **40 mins**
- [x] ~Resolve any issues revealed by Percy on vita-min & track the amount of work~ No issues found

## Time spent makes PRs

**100 minutes** to create PR in all three product apps.

## Time that PR's take to merge

- [x] SHIBA - Opened on **2021-09-16**, Merged on **2021-09-16**  - Same day
- [x] GCF - Opened on **2021-09-16**, Merged on **2021-09-16**  - Same day
- [x] GYR - Opened on **2021-09-16**, Merged on **2021-09-16**  - Same day
